source 'http://rubygems.org'

gem 'rails', '3.1.1'

# ERB alternative
gem 'haml'
# Pagination
gem 'kaminari' 
# Authentication
gem 'devise'
gem 'cancan'

# Better db queries
gem 'squeel'

# database in production
gem 'pg'
# database in devo/test
gem 'sqlite3'


# bootstrap - UI 
gem 'bootstrap-sass'

gem 'bundler', '1.1.rc'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.1.4'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
end

# Default javascript library
gem 'jquery-rails'

# use pjax instead of ajax!
gem 'pjax_rails'

# comments
gem 'acts_as_commentable_with_threading', :git => 'https://github.com/elight/acts_as_commentable_with_threading.git'
# votes
gem 'acts_as_votable'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

group :test do
  # Pretty printed test output
  gem 'turn', :require => false

end
  
group :development do

  # Console
  gem 'pry'
  gem 'pry-remote' # for pow
  gem 'map_by_method' # Helper for pry
  
  # Guard
  gem 'guard-livereload'
  gem 'guard-bundler'
  
  gem 'rb-fsevent', :require => false if RUBY_PLATFORM =~ /darwin/i
  
  gem 'rails_best_practices'
  
end